Contact form section
Carshy/portfolio-skeleton-mobile pull request #3
Opened 2022-06-08 11:17 UTC by Amanulla

### Contact form
- Done validation for the email field of the contact form.

2022-06-08 15:07 UTC, muneebulrehman requested changes
Hi @Carshy  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good PR description
- Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 15:07 UTC, muneebulrehman commented on index.html
> +                <form action="#" method="post">
Your form should submit the data to formspree. Kindly update it.

2022-06-08 15:07 UTC, muneebulrehman commented on index.html
> +                            <textarea class="txtarea-bx" max="500" required>Write your message here</textarea>
It would be better if you used a placeholder instead of anchored text in the field. In your case, the message is going to be there even when the user clicks on the text area.

2022-06-08 15:07 UTC, muneebulrehman commented on index.html
> +                            <button class="btn-inpt" type="button">Get In Touch</button>
The submit button needs to have the `type = submit`  or with no type attribute (note that it defaults to a submit type when no type attribute is used.)

2022-06-08 15:07 UTC, muneebulrehman commented on index.html
> +                            <input class="inpt-bx" type="text" name="name_text" id="name" max="30" placeholder="Enter your name here" required>
Kindly correct the `max` to `maxlength`.  Both of these are two different attributes.

2022-06-08 15:07 UTC, muneebulrehman commented on index.html
> +                            <textarea class="txtarea-bx" max="500" required>Write your message here</textarea>
Kindly correct the `max` to `maxlength`.  Both of these are two different attributes.

2022-06-08 16:54 UTC, Carshy commented
I made changes as requested by the reviewer. @Amanulla  thanks for the review changes made as requested

2022-06-08 17:15 UTC, vechicin requested changes
# Hi @Carshy  ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job implementing the changes requested by the previous reviewer.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 17:15 UTC, vechicin commented on styles/style.css
> +}
Your contact section doesn't quite look like the one from the template design.

Your design:

<img width="171" alt="Screen Shot 2022-06-08 at 12 06 53" src="https://user-images.githubusercontent.com/82426682/172675736-ae2f8c87-c7d0-4aeb-925b-79fe62d583ab.png">

The template design:

<img width="238" alt="Screen Shot 2022-06-08 at 12 07 12" src="https://user-images.githubusercontent.com/82426682/172675786-a297d85e-3718-489d-9a99-f832d1f902cd.png">

The background image is not correctly placed and the margins are not quite the same. There is also a strange margin to the right that is present all throughout your design. Kindly fix all of these issues as it is a project requirement.

<img width="895" alt="Screen Shot 2022-06-08 at 12 08 40" src="https://user-images.githubusercontent.com/82426682/172676097-89a773f7-0adb-4c0d-b35f-5fe6176c094c.png">

2022-06-08 17:15 UTC, vechicin commented on index.html
> +                        </li>
There is a strange behavior in your input fields and submission button which makes for bad UI/UX. The reason for it is because you wrapped them inside `<li>`. I recommend you remove the `<ul>` and `<li>` and simply layout your inputs and button directly within the `<form>`.

<img width="336" alt="Screen Shot 2022-06-08 at 12 10 53" src="https://user-images.githubusercontent.com/82426682/172676660-14dc7ad8-25e0-4cdf-9e18-5c747570a1e4.png">

2022-06-08 17:15 UTC, vechicin commented on styles/style.css
> +}
Your button interaction styling doesn't quite match that of the template design.

<img width="317" alt="Screen Shot 2022-06-08 at 12 13 03" src="https://user-images.githubusercontent.com/82426682/172677031-24c48e4b-43b9-480d-8911-d42b0ff45637.png">

Kindly fix this as it is a project requirement.

<img width="902" alt="Screen Shot 2022-06-08 at 12 13 34" src="https://user-images.githubusercontent.com/82426682/172677105-482e340a-b874-4ac9-9d04-a3e20b1626cd.png">

2022-06-09 15:13 UTC, Carshy commented
Made changes as requested.  @vechicin thanks for the feedback it was really helpful

2022-06-09 15:22 UTC, Deepakdanger approved these changes
Hi @Carshy, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- _Check the comment below._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 15:22 UTC, Deepakdanger commented on index.html
> +                    <!-- <div class="contacts-lists"> -->
- [ ]  [OPTIONAL] Kindly remove the commented code.

2022-06-09 15:22 UTC, Deepakdanger commented on index.html
> +                    <!-- </div> -->
- [ ]  [OPTIONAL] Kindly remove the commented code.

2022-06-09 15:22 UTC, Deepakdanger commented on index.html
> +                        </div>
- [ ]  [OPTIONAL] There is also no need of div , instead of designing div you can design the `<input>, < textarea>` also. For future requirements, Kindly fix it.

2022-06-09 16:24 UTC, merged